[package]
name = "renmap"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "^0", features = ["wgpu", "tokio", "image"] }
iced_aw = { version = "^0", default-features = false, features = ["menu"] }
